### ISSUE TITLE
K-Line

### ISSUE THREAD

**Issue by ircer** [jjyg/rbircd#3]
Hi,

Is it possible that you can add a K-Line command?

Cheers,
Jack

**Comment by ircer** [comment]
Is it possible @jjyg?

What is the best way for us to implement it?

**Comment by jjyg** [comment]
Everything is possible, modulo a small patch :)

For KLines, i'd add a check against a blacklist in Port#can_read against fd.peer_addr after https://github.com/jjyg/rbircd/blob/master/ircd.rb#L262 , but you'd also need to add a way to persist the list across process restarts. I guess a new configuration line like 'K:/path/to/file' would be required, and the matching KLINE command (for opers only).

**Comment by ghost** [comment]
Can you implement it maybe? :+1:

**Comment by jjyg** [comment]
Nah, my ircd is not adapted against 'bad' users. If you really want to deploy it on an 'hostile' network, there are many checks and limitation that would need to be implemented on top of that.
